# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Personal info
name: Timothy Faron
title: Systems/Software Engineer V
email: tfaron@gmail.com
# website: www.github.com/sproogen/resume-theme

# Social links
# twitter_username: facespics
# github_username:  sproogen
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: chillwildlife
linkedin_username: tim-faron-58724a95
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll

# About Section
# about_title: Summary
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Highly motivated software engineer known for attention to detail and outstanding technical proficiencies. Extensive experience specializing in enabling rapid development through automated testing. Dedicated team player with the keen ability to analyze, design and implement multiple projects/solutions simultaneously. Proven adaptive self-starter with strong communication, planning and implementation skills for quality and product release initiatives.

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# More Section
more_title: Certificates
more_content: | # this will include new lines to allow paragraphs
  Certified SilkTest Engineer (CSTE)

# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
